#!/usr/bin/env python3

import os, subprocess, shutil, psutil, time
from datetime import datetime

disk_usage_percent = psutil.disk_usage("/").percent
cpu_usage = psutil.cpu_percent(interval=1)
memory_usage_percent = psutil.virtual_memory().percent
system_uptime = time.time() - psutil.boot_time()
readable_uptime = time.strftime("%H:%M:%S", time.gmtime(system_uptime))

# Initialize CPU usage measurement
for proc in psutil.process_iter():
    try:
        proc.cpu_percent(interval=None)
    except (psutil.NoSuchProcess, psutil.AccessDenied):
        pass

time.sleep(1)

# Wait to allow CPU usage calculation
processes = []
for proc in psutil.process_iter(['pid', 'name', 'cpu_percent']):
    try:
        processes.append(proc.info)
    except (psutil.NoSuchProcess, psutil.AccessDenied):
        pass


top_processes = sorted(processes, key=lambda p: p['cpu_percent'], reverse=True)[:5]

print(f"disk usage: {disk_usage_percent}%")
print(f"cpu usage: {cpu_usage}%")
print(f"memory usage: {memory_usage_percent}%")
print(f"system uptime: {readable_uptime}")
print("Top 5 CPU-consuming processes:")
for p in top_processes:
    print(f"PID: {p['pid']:<6} Name: {p['name']:<20} CPU: {p['cpu_percent']:>5}")
